# -*- coding: utf-8 -*-
"""CH4_1-8_AKP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qJ0yrpyzdtIJE6V0tuLmXfWeYoSZd35X
"""

#1
#Write a program that reads a positive integer n
#and prints the sum of all natural numbers from 1 to n,
#using a for loop and the range() function.
'''
n = int(input())
sum = 0
for i in range(1, n+1):
    sum += i
print(sum)
'''
#2
#Write a program that prints the multiplication table of a given number,
#for a given number of rows, using a for loop with range().
'''
num = int(input())
row = int(input())
for i in range(1, row+1):
    print(num,'x', i, '=', num*i)
'''
#3
#Write a program that reads a positive integer and counts how many digits it has,
#using a while loop — without converting the number to a string.
'''
n = int(input())
digit = 0
while n > 0:
    n = n//10
    digit += 1
print(digit)
'''
#4
#Write a program that reads an integer n and prints a
#right-angled triangle pattern made of stars with n rows,
#where row i contains exactly i stars.
'''
n = int(input())
for i in range(1, n+1):
    print(i*'*')
'''
#5
#Write a program that reads a positive integer
#and prints it with its digits reversed, using a while loop.
'''
n1 = int(input())
n2 = ''
if n1%10 != 0:
    while n1 > 0:
        n2 += str(n1%10)
        n1 = n1//10
else:
    while n1%10 == 0:
        n1 = n1//10
    if n1%10 != 0:
        while n1 > 0:
            n2 += str(n1%10)
            n1 = n1//10
n2 = int(n2)
print(n2)
'''
#6
#The Fibonacci series starts 0, 1, 1, 2, 3, 5, 8, ... where each term is the sum
#of the two terms before it. Write a program that reads an integer n,
#generates the first n terms of the series using a for loop,
#and prints the sum of those n terms.
'''
n = int(input())
f1 = 0
f2 = 1
f3 = 1
if n >= 3:
    sum = 2
    for i in range(2, n-1):
        f3 = f1 + f2
        f1 = f2
        f2 = f3
        f3 = f1 + f2
        sum += f3
elif n == 2:
    sum = 1
else:
    sum = 0
print(sum)
'''
#7
#Write a program that reads an integer n and prints a diamond pattern made of stars:
#n rows that grow wider (the top/upper half, ending at the widest middle row), followed by n − 1 rows
#that shrink back down (the lower half),
#with each row centered using leading spaces.
'''
n = int(input())
n1 = 1
for i in range (1, n+1):
    print((n-i)*' ','*'*n1, sep = '')
    n1 += 2
n1 -= 4
for i in range (1, n):
    print(i*' ', n1*'*', sep = '')
    n1 -= 2
'''
#8
#Write a program that reads two integers L and R and prints every prime number
#in the inclusive range [L, R], separated by spaces, on a single line.
#Use nested loops: an outer loop that walks through each number in the range,
#and an inner loop that tests whether that number is prime.
#If no primes exist in the range, print "No Primes Found" instead.
l = int(input())
r = int(input())
prime_list = []
for i in range(l, r+1):
  if i < 2:
    continue
  is_prime = True
  for j in range(2, int(i**0.5)+1):
    if i%j == 0:
      is_prime = False
      break
  if is_prime:
    prime_list.append(i)
if len(prime_list) > 0:
  print(*(prime_list))
else:
  print('No Primes Found')