# -*- coding: utf-8 -*-
"""ch5_1-7_AKP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qJ0yrpyzdtIJE6V0tuLmXfWeYoSZd35X
"""

#1
#Write a program that reads a positive integer n and prints the sum of all
#even numbers from 1 to n (inclusive), using a for loop.
'''
n = int(input())
sum = 0
for i in range(1, n+1):
    if i%2 == 0:
        sum += i
print(sum)

'''
#2
#Write a program that reads n integers, one per line, and finds the second
#largest value among them. Do this in a single pass using a for loop — do not
#store and sort the whole list. You can assume all n values are distinct.
'''
n = int(input())
max1 = -10**(6)
max2 = -10**(6)
for i in range(1, n+1):
    current = int(input())
    if (current > max1) and (current > max2):
        max2 = max1
        max1 = current
    elif current > max2:
        max2 = current
print(max2)
'''
#3
#An ancient vault contains numbered doors. A door numbered x can only be opened
#if the digits of x are strictly increasing from left to right — every digit
#must be strictly greater than the digit immediately before it. For example,
#123 is valid (1 < 2 < 3), but 132 is not (3 > 2), and 122 is not either
#(2 = 2 — equal adjacent digits don't count as increasing). Given two integers
#L and R, count how many door numbers in the inclusive range [L, R] are valid.
#A single-digit number is always considered valid. This problem comes
#with strict rules on how you're allowed to solve it
#(matching how it will appear on HackerRank):
#Use for loops only — no while loops anywhere.
#Do not store digits in a list, array, or any other container.
#Do not convert the number to a string.
#Do not use recursion.
#Do not hardcode which numbers are valid.
#Check digits mathematically, using only % (remainder) and // (integer division).
'''
l = int(input())
r = int(input())
max1 = 0
max2 = 0
count = 0
if (l<10) and (r<10):
    print(r)
else:
    for i in range(l, r):
        for j
        if i > 0:
            max1 = i%10
            max2 = (i//10)%10
            if (max1 > max2):
                i = i//10
        count += 1
    print(count)
'''
#4
#A 3-digit number is called an Armstrong number if the sum of the cubes of
#its digits equals the number itself. For example, 153 is an Armstrong number
#because 1³ + 5³ + 3³ = 1 + 125 + 27 = 153. Write a program that reads a 3-digit
#number and checks whether it is an Armstrong number, using a while loop to
#extract digits with the modulus (%) and floor division (//) operators —
#do not convert the number to a string.

#I did it simplier my own way
'''
n = int(input())
if (n%10)**3 + ((n//10)%10)**3 + (n//100)**3 == n: #I did it simplier my own way
    print('Armstrong Number')
else:
    print('Not an Armstrong Number')
'''
#5
#A perfect number is a positive integer that equals the sum of its own proper
#divisors (all divisors of the number except the number itself).
#For example, 6 is perfect because 1 + 2 + 3 = 6, and 28 is perfect
#because 1 + 2 + 4 + 7 + 14 = 28.
#Write a program that reads two integers L and R and finds every
#perfect number in the inclusive range [L, R]. Use a nested loop:
#an outer loop over every candidate number in the range,
#and an inner loop that sums up its proper divisors.
'''
l = int(input())
r = int(input())
sum = 0
count = 0
for i in range(l, r+1):
    for j in range(1, i):
        if i%j == 0:
          sum += j
    if sum == i:
      print(sum, end = ' ')
      count += 1
    sum = 0
if count == 0:
    print('No Perfect Numbers Found')
'''
#6
#A strong number is a number whose digits, each replaced by its own factorial
#and then summed together, add up to the original number. For example, 145 is
#a strong number because 1! + 4! + 5! = 1 + 24 + 120 = 145.
#Write a program that reads a number and checks whether it is a strong number.
#Since no built-in factorial function is allowed, compute the factorial of each
#digit yourself, using a second (inner) loop — one loop extracts digits,
#and for every digit extracted, another loop computes that digit's
#factorial from scratch.
'''
n = int(input())
k = n
fac = 1
sum = 0
while k > 0:
    last = k%10
    for i in range(1, last+1):
        fac = i*fac
    sum += fac
    fac = 1
    k = k//10
if sum == n:
    print('Strong Number')
else:
    print('Not a Strong Number')
'''
#7
#Floyd's Triangle is a right-angled triangle of consecutive natural numbers,
#where row i contains i numbers, and the numbering keeps counting up continuously
#from where the previous row left off (it does NOT restart at 1 for each row).
#Write a program that reads n and prints the first n rows of Floyd's Triangle.
#This needs a counter variable that persists across the entire nested loop —
#it should NOT be reset inside the outer loop.
'''
n = int(input())
count = 1
for i in range(1, n + 1):
  for j in range(1, i + 1):
      print(count, end = ' ')
      count += 1
  print()
'''