# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PcOt3jlUt96qyef0UH1pzspnCiWGg3yV
"""

#1
#Write a program that reads an integer n and prints a pyramid of n rows,
#where row i climbs from 1 up to i and then back down to 1 again,
#forming a numeric palindrome on every row — for example, row 4 reads 1234321.
#Each row is centered using leading spaces, so the widest row (row n) sits
#flush against the left edge and every row above it is indented a little more.
'''
n = int(input())
for i in range(1, n+1):
    print(' '*(n-i), end ='')
    for j in range(1, i+1):
        print(j, sep = '', end = '')
    for f in range(i-1, 0, -1):
        print(f, end = '')
    print()
'''
#2
#The digital root of a number is found by summing its digits,
#and if the result still has more than one digit, summing those digits again
#— repeating until a single digit remains.
#Write a program that reads a number n, finds its digital root,
#and reports how many separate rounds of digit-summing it took to get there.
'''
n = int(input())
count = 0
while n >= 10:
    dig = 0
    while n>0:
        dig += n%10
        n = n//10
    n = dig
    count += 1
print(n)
print(count)
'''
#3
#Take any 4-digit number where the digits aren't all identical.
#Rearrange its digits into descending order to form one number,
#and into ascending order to form another, then subtract the smaller from the larger.
#Now repeat the exact same process on the result.
#Remarkably, no matter which 4-digit number you start from
#(as long as its digits aren't all the same), this process always reaches exactly 6174
#— known as Kaprekar's constant — within at most 7 repetitions.
#Once it reaches 6174, it stays there forever (6174 → 7641 − 1467 = 6174).
'''
n = int(input())
count = 0
while n != 6174:
    a = n // 1000
    b = (n // 100) % 10
    c = (n // 10) % 10
    d = n % 10
    if a > b:
        z = a
        a = b
        b = z
    if c > d:
        z = c
        c = d
        d = z
    if a > c:
        z = a
        a = c
        c = z
    if b > d:
        z = b
        b = d
        d = z
    if b > c:
        z = b
        b = c
        c = z
    n1 = a * 1000 + b * 100 + c * 10 + d
    n2 = d * 1000 + c * 100 + b * 10 + a
    n = n2 - n1
    count += 1
print(count)
'''