# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PcOt3jlUt96qyef0UH1pzspnCiWGg3yV
"""

#1
#A teacher wants a quick way to see how a class performed.
#The passing mark for the exam is 40. Given the marks of n students,
#write a program that counts how many students passed and calculates
#what percentage of the class that represents, using a for loop.
'''
a = int(input())
b = int(input())
c = int(input())
total = 0
for i in range(1, c+1):
    total += a
    a += b
print(total)
'''
#2
#A teacher wants a quick way to see how a class performed.
#The passing mark for the exam is 40. Given the marks of n students,
#write a program that counts how many students passed and calculates
#what percentage of the class that represents, using a for loop.
'''
n = int(input())
passed = 0
for i in range(n):
    mark = int(input())
    if mark >= 40:
        passed += 1
percent = (passed / n) * 100
print('Passed:', passed)
print(f"Pass Percentage: {percent:.2f}%")
'''
#3
#The k-th triangular number is the sum of every whole number from 1 to k
#(so the 4th triangular number is 1+2+3+4 = 10). Given n, write a program
#that finds the sum of the first n triangular numbers:
#T(1) + T(2) + ... + T(n). Use two nested for loops — do not use a shortcut
#formula for either the triangular numbers or their sum.
'''
n = int(input())
num = 0
for i in range(1, n+1):
    for j in range(1, i+1):
        num += j
print(num)
'''

