# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PcOt3jlUt96qyef0UH1pzspnCiWGg3yV
"""

#1
#A text-analysis tool needs to break a line of text down by what kind of
#characters it contains. Write a program that reads one line of text and counts
#how many vowels, consonants, digits, and spaces it has. Vowels are the letters
#a, e, i, o, u in either uppercase or lowercase. Every other letter (including y)
#counts as a consonant. Punctuation and any other symbols are not counted in any category.
'''
s = input()
s = s.lower()
vowels = 'aeiou'
vowels_count = 0
consonants_count = 0
digits = '1234567890'
digits_count = 0
spaces_count = 0
for i in s:
    if i.isalpha() == True:
        if i in vowels:
            vowels_count += 1
        else:
            consonants_count += 1
    elif i in digits:
        digits_count += 1
    elif i == ' ':
        spaces_count += 1
print('Vowels:', vowels_count)
print('Consonants:', consonants_count)
print('Digits:', digits_count)
print('Spaces:', spaces_count)
'''
#2
#Write a program that reads a line of text and finds the letter that appears
#most often in it. Letters are counted without regard to case, so 'A' and 'a'
#are the same letter, and anything that isn't a letter
#(digits, spaces, punctuation) is ignored.
#If two or more letters are tied for the highest count,
#print the one that comes first in the alphabet.
'''
s = input()
s = s.lower()
max1 = 0
count = 0
maxchar = ''
for i in range(97, 123):
    char = chr(i)
    count = 0
    for j in s:
        if j == char:
            count += 1
    if count > max1:
        max1 = count
        maxchar = char
print(maxchar, max1)
'''